courses = ["History","Maths","Physics","CompSci"]
print(courses)
print(courses[0])
print(courses[3])
print(courses[-1]) #last item
print(courses[0:2])
print(courses[:3])
print(courses[1:])
print(courses[0:2])
print(courses.index("Maths"))
print("Maths" in courses)
courses.append("Art")
print(courses)
courses.insert(0,"Che")
print(courses)
courses2 = ["Art","Edu"]
courses.insert(0,courses2)
print(courses)
courses.extend(courses2)
print(courses)
courses.remove("Maths")
print(courses)
popped=courses.pop()
print(popped)
print(courses)
courses.reverse()
print(courses)
num = [1,5,3,2,6]
print(num)
num.sort()
print(num)
num.sort(reverse=True)
print(num)
s_num = sorted(num)
print(s_num)
print(min(s_num))
print(max(s_num))
print(sum(s_num))

for i,j in enumerate(courses, start=1):
    print(i,j)
